apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: j0n4t4n/mqtt-iot-pipeline
        ports:
        - containerPort: 8080
        env:
          - name: MOSQUITTO_URI
            valueFrom:
              secretKeyRef:
                name: backend-mosquitto-secret
                key: uri
          - name: MOSQUITTO_USER
            valueFrom:
              secretKeyRef:
                name: backend-mosquitto-secret
                key: user
          - name: MOSQUITTO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-mosquitto-secret
                key: password
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 5
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-mosquitto-secret
data:
  uri: "tcp://prod184.container.demo.local:10057"
  user: "ezmeral"
  password: "NMH4JieRkWb!LH79KmZW6sNwWJ!E9X"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-deployment-svc
  labels:
    hpecp.hpe.com/hpecp-internal-gateway: "true"
    hpecp.hpe.com/portname-override: "http-backend"
spec:
  selector:
    app: backend
  type: NodePort
  ports:
  - name: backend-service
    protocol: TCP
    port: 8080
    targetPort: 8080
