apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: pbork/frontend-mybaumarkt:dev
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-deployment-svc
  labels:
    hpecp.hpe.com/hpecp-internal-gateway: "true"
    hpecp.hpe.com/portname-override: "http-frontend"
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
  - name: frontend-service
    protocol: TCP
    port: 3000
    targetPort: 3000
