apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender-deployment
spec:
  selector:
    matchLabels:
      app: recommender
  replicas: 1
  template:
    metadata:
      labels:
        app: recommender
    spec:
      containers:
      - name: recommender
        image: ancesp/recommender-system
        ports:
        - containerPort: 1234
---
apiVersion: v1
kind: Service
metadata:
  name: recommender-deployment-svc
  labels:
    hpecp.hpe.com/hpecp-internal-gateway: "true"
    hpecp.hpe.com/portname-override: "http-recommender"
spec:
  selector:
    app: recommender
  type: NodePort
  ports:
  - name: recommender-service
    protocol: TCP
    port: 1234
    targetPort: 1234
